### ISSUE TITLE
Lightkeeper - 2 'undefined' calls are made to Root.js on launch

### ISSUE THREAD

**Issue by etcadinfinitum** [aarya22/noschoolviolence#2]
On launching the chatbot in console, two output cycles are completed before any input is received from the user. It appears that something is making two calls to Root.js.

Output on console:
```
➜  lightkeeper git:(lightkeeper) ✗ nodemon .
[nodemon] 1.17.4
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node .`
Hi, I'm Lightkeeper, and I'm here to help you help a child. Would you like to profile a student?
You entered undefined
Checking our index of 8 behaviors
That behavior isn't part of our standard set of problematic behaviors, but I will add it to the list.
The concerning behavior has been added to my profile for this session. Feel free to keep adding concerns.
You entered undefined
Checking our index of 8 behaviors
That behavior isn't part of our standard set of problematic behaviors, but I will add it to the list.
The concerning behavior has been added to my profile for this session. Feel free to keep adding concerns.
```

@codefoster Your help would be greatly appreciated!

[if I figure it out or the behavior *magically* disappears, I'll close the issue]

**Comment by codefoster** [comment]
It's because there are two events that occur when you first fire up a bot - the user enters the conversation and the bot enters the conversation. You have to filter for "message" to respond only to user utterances.

**Comment by etcadinfinitum** [comment]
Makes so much sense! thank you
