### ISSUE TITLE
Lightkeeper - centralize REST calls in a single API?

### ISSUE THREAD

**Issue by etcadinfinitum** [aarya22/noschoolviolence#3]
For simplicity and improved modularity, it makes sense to centralize external requests that the bot will make (get behavior dictionary, post new request for analysis, get insights for specific individual, get all insights, etc). A single API would allow easier integration for a web form and vastly improve maintainability. 

Additionally, intermediate processing of the bot's I/O may be required (converting data format A to format B, etc).

**Comment by codefoster** [comment]
Good thinking. I might recommend an ApiService in the bot project that has simple methods that can be used by any topics (i.e. `apiService.recordConcern(1234, "angry")`).
